repos:
- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.64.1 # Get the latest from: https://github.com/antonbabenko/pre-commit-terraform/releases
  hooks:
    - id: terraform_docs # https://github.com/terraform-docs/terraform-docs
    - id: terraform_fmt # https://www.terraform.io/cli/commands/fmt#usage
    - id: terraform_tflint # https://github.com/terraform-linters/tflint/tree/master/docs
      args:
        - --args=--module
        - --args=--config=__GIT_WORKING_DIR__/.tflint.hcl
        - --args=--enable-rule=terraform_comment_syntax
        - --args=--enable-rule=terraform_deprecated_index
        - --args=--enable-rule=terraform_documented_variables
        - --args=--enable-rule=terraform_documented_outputs
        - --args=--enable-rule=terraform_naming_convention
        - --args=--enable-rule=terraform_standard_module_structure
        - --args=--enable-rule=terraform_typed_variables
        - --args=--enable-rule=terraform_unused_declarations
        - --args=--enable-rule=terraform_unused_required_providers
    - id: terraform_tfsec # https://github.com/aquasecurity/tfsec/tree/master/docs/guides/configuration
    - id: terraform_validate # https://www.terraform.io/cli/commands/validate
    - id: terragrunt_fmt # https://terragrunt.gruntwork.io/docs/reference/cli-options/#hclfmt
    - id: terragrunt_validate # Terragrunt forwards validate command directly to Terraform